/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizerRouteImport } from './routes/visualizer'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as LoginCallbackRouteImport } from './routes/login-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login-callback',
  path: '/login-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-callback': typeof LoginCallbackRoute
  '/sign-out': typeof SignOutRoute
  '/visualizer': typeof VisualizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-callback': typeof LoginCallbackRoute
  '/sign-out': typeof SignOutRoute
  '/visualizer': typeof VisualizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-callback': typeof LoginCallbackRoute
  '/sign-out': typeof SignOutRoute
  '/visualizer': typeof VisualizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/login-callback' | '/sign-out' | '/visualizer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/login-callback' | '/sign-out' | '/visualizer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/login-callback'
    | '/sign-out'
    | '/visualizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
  SignOutRoute: typeof SignOutRoute
  VisualizerRoute: typeof VisualizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-callback': {
      id: '/login-callback'
      path: '/login-callback'
      fullPath: '/login-callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LoginCallbackRoute: LoginCallbackRoute,
  SignOutRoute: SignOutRoute,
  VisualizerRoute: VisualizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
